language: minimal

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    sources:
      - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
      - build-essential
      - gcc-arm-embedded
      - imagemagick
      - libfreetype6-dev
      - libjpeg-dev
      - libpng-dev
      - pkg-config

  homebrew:
    packages:
      - numworks-sdk
    taps: numworks/tap
    update: true

matrix:
  include:
    - os: linux
      env: PLATFORM=device
    - os: linux
      env: PLATFORM=simulator
      apt:
        packages:
          - libx11-dev
          - libxext-dev
    - language: android
      env: PLATFORM=simulator TARGET=android
      android:
        components:
          - tools
          - platform-tools
          - extra-google-m2repository
          - extra-android-m2repository
      install:
        - echo y | sdkmanager "ndk-bundle"
    - os: linux
      env: PLATFORM=blackbox QUIZ_USE_CONSOLE=1
    - os: osx
      env: PLATFORM=simulator
    - os: osx
      env: PLATFORM=simulator TARGET=ios GOOGLE_ANALYTICS=0

script:
- set -e
- make
- if [ "$PLATFORM" = "blackbox" ]; then make test.bin; output/release/blackbox/test.bin; PLATFORM=blackbox make integration_tests; fi
