name: Continuous integration
on: [push]

jobs:
  build-msys2:
    runs-on: windows-latest
    steps:
      - uses: ecco/setup-msys2@master
      - uses: actions/checkout@v1
      - run: env
      - run: set
      - run: dir D:
      - run: dir D:\a\_temp
      - run: dir D:\a\_temp\plifplafplouf
      - run: D:\a\_temp\plifplafplouf\usr\bin\bash.exe -l -i -c "env"
      - run: D:\a\_temp\plifplafplouf\usr\bin\bash.exe -l -i -c "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-pkg-config mingw-w64-x86_64-make mingw-w64-x86_64-python3 mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng"
      - run: D:\a\_temp\plifplafplouf\usr\bin\bash.exe -l -i -c "cd $OLDPWD && make PLATFORM=simulator"
