name: Continuous integration
on: [push]

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: ecco/setup-emscripten@master
      - run: source emsdk/emsdk_env.sh && make PLATFORM=emscripten
  build-windows:
    runs-on: windows-latest
    steps:
      - run: wget http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe
      - run: wget https://raw.githubusercontent.com/msys2/msys2-installer/master/auto-install.js
      - run: msys2-x86_64-20190524.exe --platform minimal --script auto-install.js -v
      - uses: actions/checkout@v1
      - run: make PLATFORM=simulator
        shell: bash
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libfltk1.3-dev
      - uses: actions/checkout@v1
      - run: make PLATFORM=simulator
  build-macos:
    runs-on: macOS-latest
    steps:
      - run: brew install numworks/tap/numworks-sdk
      - run: brew install fltk
      - uses: actions/checkout@v1
      - run: make PLATFORM=simulator
