name: Continuous integration
on: [push]

jobs:
  build-n0100:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install binutils-arm-none-eabi build-essential gcc-arm-none-eabi imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: actions/checkout@v1
      - run: make -j2 MODEL=n0100 epsilon.dfu
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-n0100.zip
          path: output/release/device/n0100/epsilon.dfu
  build-n0110:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install binutils-arm-none-eabi build-essential gcc-arm-none-eabi imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: actions/checkout@v1
      - run: make -j2 epsilon.dfu
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-n0110.zip
          path: output/release/device/n0110/epsilon.dfu
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: ecco/setup-msys2@master
      - uses: actions/checkout@v1
      - run: msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-pkg-config make mingw-w64-x86_64-python3 mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng
      - run: msys2do make -j2 PLATFORM=simulator
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-windows.exe
          path: output/release/simulator/windows/epsilon.exe
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: ecco/setup-emscripten@master
      - uses: actions/checkout@v1
      - run: source $EMSDK/emsdk_env.sh && make -j2 PLATFORM=simulator TARGET=web
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-web.zip
          path: output/release/simulator/web/simulator.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: actions/checkout@v1
      - run: make -j2 PLATFORM=simulator
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-linux.zip
          path: output/release/simulator/linux/epsilon.bin
  build-macos:
    runs-on: macOS-latest
    steps:
      - run: brew install numworks/tap/numworks-sdk
      - uses: actions/checkout@v1
      - run: make -j2 PLATFORM=simulator
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-macos.zip
          path: output/release/simulator/macos/app/Payload
  build-ios:
    runs-on: macOS-latest
    steps:
      - run: brew install numworks/tap/numworks-sdk
      - uses: actions/checkout@v1
      - run: make -j2 PLATFORM=simulator TARGET=ios GOOGLE_ANALYTICS=0
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-ios.zip
          path: output/release/simulator/ios/app/epsilon.ipa
