name: Continuous integration
on: [push]

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: ecco/setup-emscripten@master
      - uses: actions/checkout@v1
      - run: make PLATFORM=emscripten
