name: Continuous integration
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - run: make PLATFORM=simulator
        shell: bash
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make PLATFORM=simulator
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: make PLATFORM=simulator
