name: Metrics
on: [push, pull_request]

jobs:
  binary-size:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@v1
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      - run: make -j2 -C base epsilon.dfu
      - run: echo "::set-env name=BASE_SIZE::$(arm-none-eabi-size base/output/release/device/n0110/epsilon.elf)"
      - uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment ${{ env.BASE_SIZE }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: head
      - run: make -j2 -C head epsilon.dfu
      - run: echo "::set-env name=HEAD_SIZE::$(arm-none-eabi-size head/output/release/device/n0110/epsilon.elf)"
      - uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment ${{ env.HEAD_SIZE }}
